[HMA-3448] Change duplicate header content
hmrc/paye-tax-calculator-frontend pull request #137
Opened 2020-08-25 15:37 UTC by mrolfe88

Remove back button from nav landmark

2020-08-25 15:39 UTC, georgeherby requested changes

2020-08-25 15:39 UTC, georgeherby commented on app/views/pages/ResultDetailView.scala.html
> +@h2(Messages("quick_calc.result.total_deductions.info_a") + " " + label.toLowerCase + "ly " + Messages("quick_calc.result.total_deductions.info_b"))
Pretty sure there are labels with ly. ALSO you need this in a message file to we can support welsh

2020-08-25 15:39 UTC, georgeherby commented on app/views/pages/ResultDetailView.scala.html
> +    @h2(Messages("quick_calc.result.how_we_calculate_a") + " " + label.toLowerCase + "ly " + Messages("quick_calc.result.how_we_calculate_b"))
Same here

2020-08-25 15:39 UTC, georgeherby commented on app/views/pages/ResultDetailView.scala.html
> +    @h2(Messages("quick_calc.result.how_we_calculate_a") + " " + label.toLowerCase + "ly " + Messages("quick_calc.result.how_we_calculate_b"))
same here

2020-08-25 16:16 UTC, mrolfe88 commented
test this please

2020-08-26 11:52 UTC, mrolfe88 commented
test this please

2020-08-26 14:57 UTC, merged